# https://developer.tdameritrade.com/content/streaming-data
SUB_TYPES = {
    "news": (
        "NEWS_HEADLINE",
        "SUBS",
        "NEWS_HEADLINE-SUBS",
        [
            "symbol",
            "error",
            "timestamp",
            "headline_id",
            "status",
            "headline",
            "story_id",
            "keyword_counts",
            "keywords",
            "is_hot",
            "source",
        ],
        [0, 3, 4, 5, 8],
        {},
    ),
    "forex": (
        "LEVELONE_FOREX",
        "SUBS",
        "LEVELONE_FOREX-SUBS",
        [
            "symbol",
            "bid",
            "ask",
            "last_price",
            "bid_size",
            "ask_size",
            "volume",
            "last_size",
            "quote_time",
            "trade_time",
            "high",
            "low",
            "close",
            "exchange_id",
            "desc",
            "open",
            "net_change",
            "percent_change",
            "exchange",
            "digits",
            "status",
            "tick",
            "tick_amt",
            "product",
            "trading_hours",
            "tradable",
            "market_maker",
            "52_wk_high",
            "52_wk_low",
            "mark",
        ],
        [0, 1, 2, 3, 4, 5, 6],
        {},
    ),
    "quote": ("QUOTE", "SUBS", "QUOTE-SUBS", [str(f) for f in range(52)], [0, 1, 2, 3, 8], {}),
    "chart": (
        "CHART_type",
        "SUBS",
        "CHART_type-SUBS",
        [str(f) for f in range(8)],
        [0, 1, 2, 3, 4, 5, 6, 7, 8],
        {"type": {"equity": "EQUITY", "futures": "FUTURES", "options": "OPTIONS"}},
    ),
    "actives": (
        "ACTIVES_exchange",
        "SUBS",
        "ACTIVES_exchange-SUBS",
        [str(f) for f in range(5)],
        [0, 1],
        {"exchange": {"NASDAQ": "NASDAQ", "NYSE": "NYSE", "OPTIONS": "OPTIONS", "OTCBB": "OTCBB"}},
    ),
}
SUB_ID_TO_NAME = {val[2]: key for key, val in SUB_TYPES.items()}
